repos:

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      additional_dependencies:
        - typing-extensions
        - types-setuptools
      args:
        - --strict
        - --ignore-missing-imports

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      entry: pflake8
      additional_dependencies: [pyproject-flake8]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      name: Run Black (the uncompromising code formatter)
      args: [--config=./pyproject.toml]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: Run isort to sort imports in Python files
      files: \.py$|\.pyi$

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
    - id: codespell
      name: Run codespell to check for common misspellings in files
      entry: bash -c 'echo "If you think that this failure is an error, consider adding the word(s)
        to the codespell dictionary at docs/spelling_wordlist.txt.
        The word(s) should be in lowercase." && exec codespell "$@"' --
      language: python
      types: [text]
      args:
        - --ignore-words=docs/spelling_wordlist.txt

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
    - id: pydocstyle
      name: Run pydocstyle
      args:
        - --convention=pep257
        - --add-ignore=D100,D102,D103,D104,D105,D107,D205,D400,D401
      additional_dependencies:
        - 'toml'
        - 'snowballstemmer'
